### ISSUE TITLE
两个建议

### ISSUE THREAD

**Issue by kinsluck** [LiuGuoGY/JSBox-addins#2]
1. 希望能在主屏添加一个『增加新的启动器』的按钮（效果类似下图），这样当需要创建新的按钮的时候就不需要再云库里面复制再编辑了。
![1](https://user-images.githubusercontent.com/17947570/43055374-e76a97bc-8e68-11e8-99cd-386f829ecb52.png)

2. 在云库中的『上传启动器』的界面，输入了文字部分和 url scheme 之后，希望能通过点击空白处收回键盘。现在的状况是只能通过再一次点击选择图片收回键盘。

**Comment by LiuGuoGY** [comment]
好的，多谢建议！
