### ISSUE TITLE
launch center添加启动器图片问题

### ISSUE THREAD

**Issue by SadWood** [LiuGuoGY/JSBox-addins#4]
复制了APP的链接地址，但是显示这个报错
TypeError: undefined is not an object (evaluating 'resp.data.results[0].artworkUrl100')

main.js => #line 2537, column 62

本地图片选择后没有效果

**Comment by LiuGuoGY** [comment]
复制的APP链接发出来给我看一下，本地图片理论上应该可以的，你把图片也发出来看一下

**Comment by SadWood** [comment]
> 复制的APP链接发出来给我看一下，本地图片理论上应该可以的，你把图片也发出来看一下

APP链接：https://itunes.apple.com/cn/app/%E4%B8%8D%E6%80%9D%E8%AE%AE%E8%BF%B7%E5%AE%AB-g-d/id1156084215?mt=8

我试了lookup的方法确实获取不到，这个应该属于个例

图片就是下面这个，我直接从AppStore获取的APP图标
![image](https://user-images.githubusercontent.com/24450652/52834448-d8f08f00-311c-11e9-845b-3f7d2d97f391.png)

**Comment by LiuGuoGY** [comment]
添加本地图片是没有问题的，lookup 的问题我找到了，需要加个 country 参数，等我更新一下来解决。
