### ISSUE TITLE
请问一下这个iCloud同步怎么用啊。

### ISSUE THREAD

**Issue by Nergrove** [LiuGuoGY/JSBox-addins#5]
我的iPad和手机都装了这一款小插件，但是我的启动器并没有同步过去啊。

**Comment by LiuGuoGY** [comment]
同步只有在你首次安装脚本的时候才会去同步，如果已经添加了本地的启动器，那么本地就不会被覆盖，本来是要做实时同步的，但是 JSBox 生成的文件有点问题，所以不支持实时同步。
