### ISSUE TITLE
安装脚本错误

### ISSUE THREAD

**Issue by zzsnn** [LiuGuoGY/JSBox-addins#7]
获取任何脚本会不断弹窗显示以下代码：（说明，已经更到最新版本）

Error: [object BBCanvasView].setNeedsDisplay is undefined

main.js => line 0, column 842

stack => __selector
invoke
handler

**Comment by zzsnn** [comment]
Erots - 脚本商店

**Comment by LiuGuoGY** [comment]
可以描述一下你的环境，比如 iOS版本，jsbox版本，手机型号等等。

**Comment by zzsnn** [comment]
> 可以描述一下你的环境，例如iOS版本，jsbox版本，手机型号等等。

苹果6，ios12.4.8，jsbox2.11.0

**Comment by LiuGuoGY** [comment]
> > 可以描述一下你的环境，例如iOS版本，jsbox版本，手机型号等等。
> 
> 苹果6，ios12.4.8，jsbox2.11.0

重新安装一下，看看能不能正常运行。

**Comment by zzsnn** [comment]
> > > 可以描述一下你的环境，例如iOS版本，jsbox版本，手机型号等等。
> > 
> > 
> > 苹果6，ios12.4.8，jsbox2.11.0
> 
> 重新安装一下，看看能不能正常运行。

不行一样错误

**Comment by zzsnn** [comment]
> > > 可以描述一下你的环境，例如iOS版本，jsbox版本，手机型号等等。
> > 
> > 
> > 苹果6，ios12.4.8，jsbox2.11.0
> 
> 重新安装一下，看看能不能正常运行。



> > > 可以描述一下你的环境，例如iOS版本，jsbox版本，手机型号等等。
> > 
> > 
> > 苹果6，ios12.4.8，jsbox2.11.0
> 
> 重新安装一下，看看能不能正常运行。
