### ISSUE TITLE
求助，erots商店无法访问，一直显示“正在载入”

### ISSUE THREAD

**Issue by m1a1y1u1e1** [LiuGuoGY/JSBox-addins#9]
你好，最近这段时间无法访问erots，使用的设备是iphone12 pro，但是旧设备IPhone 6s 却可以正常访问。对iphone12上的erots商店尝试重装，同意用户协议后，就一直显示正在载入。
抓包分析，在同一网络下，iphone12p获取到两条链接，均有返回值
https://j3j1wl1i.api.lncldglobal.com/1.1/classes/Setting/5e4b9ae7f94e0f00083f98a6?keys=-updatedAt,-objectId,-createdAt"

https://j3j1wl1i.api.lncldglobal.com/1.1/classes/App?limit=1000&order=-updateTime,-updatedAt

iPhone6s获取到4条链接，均有返回值

https://j3j1wl1i.api.lncldglobal.com/1.1/classes/Setting/5e4b9ae7f94e0f00083f98a6?keys=-updatedAt,-objectId,-createdAt"

https://j3j1wl1i.api.lncldglobal.com/1.1/classes/App?limit=1000&order=-updateTime,-updatedAt

https://j3j1wl1i.api.lncldglobal.com/1.1/installations

https://j3j1wl1i.api.lncldglobal.com/1.1/classes/list?where=%7B%22deviceToken%22:%2252f3c418455e4b52823e290309bc5a18%22%7D

**Comment by LiuGuoGY** [comment]
关闭代理，或者换个节点
